### PR TITLE
Port Instructions from `.docx` to `.md` 

### PR DESCRIPTION
**Pull request by meawoppl**
A little more portable, and renders in github.

### CODE REVIEW

**Comment by vr2045** [comment]
Hi Matty,

On Lattice Semi's request, my company (tinyVision.ai) has taken over the
production and maintenance of the UPduino platform.

Thank you for your document! I hope you dont mind my merging your
instructions into the Github for this project here
<https://github.com/tinyvision-ai-inc/UPduino-v2.1>. I do need to modify
your instructions for the board I'm producing since the flash is a
different manufacturer and I dont have the zip file on my site yet. Check
out the changes I have planned and also feel free to fill out the online
survey <https://www.surveymonkey.com/r/HH536D8> to get your feedback.

Thank you,
Venkat

**Comment by meawoppl** [comment]
Yes please!  Also, some sort of walkthrough on how to get project -> binary
-> flashed fpga would be really helpful.  I'm pretty stuck on this.

**Comment by vr2045** [comment]
What are you stuck on? Your instructions were super detailed!

I've added the file to my Github, thank you!

**Comment by meawoppl** [comment]
Heyo, first off the vendor tools are bricked for Linux ftdi in the current release afaict. (Not your fault obviously)

The permutation of settings I have working are using the "winbond" vendor setting, component "W25Q32" as per the specification of a coworker.

**Comment by vr2045** [comment]
I prefer to use the yosys toolchain and the iceprog programmer specifically
for the download.
http://www.clifford.at/yosys/download.html
You shouldnt have any trouble since you're already on Linux.

**Comment by meawoppl** [comment]
Oh, I didn't realize that was an option! Leaving some breadcrumbs to that would have similarly saved me a bunch of time in windows-land :/

Thanks!

(Should I close this issue?)

**Comment by vr2045** [comment]
There are some prepackaged windows ports of the yosys tool chain as well if
you don't want to deal with build issues and don't mind a slightly
dated version.

I guess if your question is answered, closing is a good idea...

**Comment by meawoppl** [comment]
Thanks again!

**Pull request closed without merging**
